// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHYC68Dt2IhimZG7EQzheqEEuRm4_b39s',
    appId: '1:998954865617:web:e01c0cfe13fff34b9f46f0',
    messagingSenderId: '998954865617',
    projectId: 'instagram-a9012',
    authDomain: 'instagram-a9012.firebaseapp.com',
    storageBucket: 'instagram-a9012.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHMboxHHJRCLSI6hwgBp4hXh4QstGZeW4',
    appId: '1:998954865617:android:21214f76829660d69f46f0',
    messagingSenderId: '998954865617',
    projectId: 'instagram-a9012',
    storageBucket: 'instagram-a9012.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-lndJiWg6gmb-lxjr3z9VRbW05Yifkg',
    appId: '1:998954865617:ios:81f037e8f6fa2fbc9f46f0',
    messagingSenderId: '998954865617',
    projectId: 'instagram-a9012',
    storageBucket: 'instagram-a9012.firebasestorage.app',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-lndJiWg6gmb-lxjr3z9VRbW05Yifkg',
    appId: '1:998954865617:ios:81f037e8f6fa2fbc9f46f0',
    messagingSenderId: '998954865617',
    projectId: 'instagram-a9012',
    storageBucket: 'instagram-a9012.firebasestorage.app',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHYC68Dt2IhimZG7EQzheqEEuRm4_b39s',
    appId: '1:998954865617:web:b64fc67a814b76ed9f46f0',
    messagingSenderId: '998954865617',
    projectId: 'instagram-a9012',
    authDomain: 'instagram-a9012.firebaseapp.com',
    storageBucket: 'instagram-a9012.firebasestorage.app',
  );
}
