name: Deploy with Docker

on:
  push:
    branches: [ "main" ]   # Tự động chạy khi bạn push code lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code từ repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login Docker Hub (cần lưu username + password ở GitHub Secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build Docker image
      - name: Build Docker image
        run: docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/ev-management:latest . 

      # 4. Push Docker image lên Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ev-management:latest
