name: CI/CD Deploy to Render

on:
  push:
    branches:
      - main   # chạy khi bạn push code lên branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Đăng nhập DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 3: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ev-management-sales:latest .

      # Bước 4: Push Docker image lên DockerHub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ev-management-sales:latest
